[build]
  command = "npm run build"
  publish = "dist"

[[plugins]]
  package = "netlify-plugin-submit-sitemap"
  [plugins.inputs]

	# The base url of your site (optional, default = main URL set in Netlify)
	baseUrl = "https://frenchtechlead.com"
	sitemapPath = "/sitemap-index.xml"

  [[headers]]
    [headers.values]
      X-Content-Type-Options: nosniff # Disable MIME sniffing